### ISSUE TITLE
"dsgrid registry list" does not work out of the box

### ISSUE THREAD

**Issue by elainethale** [dsgrid/dsgrid#146]
And I think just because the default registry folder isn't made automatically. For example, that command gets to 

```
Running aws s3 sync s3://nrel-dsgrid-registry/configs ~/.dsgrid-registry/configs ...
```

But `~/.dsgrid-registry` doesn't exist yet

**Comment by daniel-thom** [comment]
This problem is related to Windows not being able to find the `aws` executable, not the `.dsgrid-registry` directory.

Problem isolation: This command fails with a file-not-found error *only on Windows*:
```
>>> subprocess.run(["aws", "help"])
```
but this command passes:
```
>>> subprocess.run(["aws.cmd", "help"])
```
This is probably a bug with aws. We can workaround it by detecting that the platform is Windows and then changing our aws commands to use `aws.cmd`. There are only two locations and both are in s3_storage_interface.py.
