### ISSUE TITLE
Subset dimensions

### ISSUE THREAD

**Issue by elainethale** [dsgrid/dsgrid#221]
Let dsgrid project coordinators define subset dimensions relative to the project's base dimensions. They should be able to fill out the base dimension file with the usual information and then append "subset columns" such as:

id | name | commercial_end_uses | residential_end_uses | transportation_end_uses
-- | -- | -- | -- | -- 
cooling_electricity | Cooling Electricity | Y | x | 
heating_electricity | Heating Electricity | x | x |
...
ev_l1l2_electricity | EV L1/L2 Electricity | | | x
...

And that should be enough to create subset dimensions useful for:
- Specifying what records are expected for different datasets
- Running filter queries
- Specifying the dimensionality of derived datasets

In this case, the subset columns are
- commercial_end_uses
- residential_end_uses
- transportation_end_uses

And the records of the associated "subset dimensions" are indicated by the rows containing any non-null data/characters in the corresponding subset column.

**Comment by daniel-thom** [comment]
@elainethale Didn't we agree that we should put these columns in a separate file, only repeating `id` so that a dataset could re-use a project's base dimension?

Secondly, are you concerned about users not reading the docs carefully and inserting `N` for `no`?

**Comment by daniel-thom** [comment]
List of development items to complete this issue:
- Add `subset_dimensions` to `ProjectConfigModel.dimensions` (in addition to `base_dimensions` and `supplemental_dimensions`).
- Extend `ProjectConfigModel.RequiredDimensionRecordsModel` to support subset dimensions.
- There are several methods in `ProjectConfig` that deal with supplemental dimensions. Extend these or add new methods to accomplish the same functionality with subset dimensions. Consider whether to add an abstraction such that call sites don't have to be concerned with the distinction between supplemental and subset dimensions.
- Extend the CLI and API commands `list_project_supplemental_dimension_query_names` (or add new ones) to support subset dimensions.
- Add a new filter model for subset dimensions in queries. (There are already filter models for base and supplemental dimensions.)
- Fix relevant tests that use supplemental dimensions for filters or aggregations.
- Fix relevant documentation.
- Refactor data repositories (StandardScenarios, EFS, test-efs) to move relevant subset dimensions from `supplemental_dimensions` to `subset_dimensions`.
- Refactor data repository project config files (StandardScenarios, EFS, test-efs) to use the subset dimensions in dataset dimension requirement sections instead of supplemental dimensions.
- Regenerate the "official" registry containing updated StandardScenarios files.
- Regenerate the filtered StandardScenarios registry that we store in the test-data repository.

**Comment by elainethale** [comment]
> @elainethale Didn't we agree that we should put these columns in a separate file, only repeating `id` so that a dataset could re-use a project's base dimension?
> 
> Secondly, are you concerned about users not reading the docs carefully and inserting `N` for `no`?

I think we went in circles on the second file:
- dsgrid backend can certainly consume this as a second file
- The dsgrid project coordinator would probably appreciate this being a single file. The task of splitting the initial single file into two files is trivial--it could be done by a script in dsgrid-project-StandardScenarios, or in dsgrid itself.

Certainly users won't read carefully and could insert an "N" or a "no". Is it better to:
- Have examples that all use x's and nulls and then just read "N" or "no" as a yes for consistency/simple code?
- Have an unadvertised (but still documented) exception that any cell whose string starts with an "N" or an "n" is counted as a no?
