### ISSUE TITLE
Add CLI commands to support dimension browsing

### ISSUE THREAD

**Issue by elainethale** [dsgrid/dsgrid#255]
- Table of dimension records
- List of dimension record ids

**Comment by daniel-thom** [comment]
Our Dash web app already supports this. Advantages over the CLI:
- Supports filtering of columns with the Dash datatable.
- Faster because it doesn’t have to load the registry on every command.

If we want something to work in a terminal then I would suggest making a TUI with [Textual](https://textual.textualize.io/). In general, the CLI is great for registering components and running queries. A GUI is better for browsing and filtering.

**Comment by elainethale** [comment]
Do we have any documentation for how to launch the web app?

**Comment by daniel-thom** [comment]
https://dsgrid.github.io/dsgrid/how_tos/browse_registry.html#project-viewer
